# MOSTRAR TODOS LOS DATOS DEL VENDEDOR CON MAS ANTIGUEDAD DEL CONCESIONARIO

SELECT * FROM vendedores ORDER BY ASC LIMIT 1;

# 30 EXTRA OBTENER DATOS DE 3 COCHEs CON MAS UNIDADES VENDIDAS 


SELECT * FROM coches WHERE id IN 
    (SELECT coche.id FROM encargos WHERE cantidad IN
(SELECT MAX(cantidad) FROM encargos));