# VISUALIZAR LOS NOMBRES DE LOS CLIENTES Y LA CANTIDAD DE LOS ENCARGOS REALIZADO 
# INCLUYENDO LOS QUE NO HAYAN REALIZADO ENCARGOS

SELECT c.nombre, COUNT(e.id) FROM clientes c
LEFT JOIN encargos e ON c.id = e.cliente_id GROUP BY 1;
