# VISUALIZAR LOS APELLIDOS DE LOS VENDEDORES SU FECHA Y NUMERO DE GRUPO ORDENADO
#  POR FECHA DESCENDENTE MOSTRAR LOS 4 ULTIMOS

SELECT apellidos, fecha, id FROM vendedores ORDER BY fecha DESC LIMIT 4;