# VISUALIZAR NOMBRE Y APELLIDOS EN UNA MISMA COLUMNA Y SU FECHA DE REGISTRO Y EL DIA DE LA SEMANA QUE SE REGISTRARON

SELECT CONCAT (nombre, ' ' , apellidos) AS 'Nombre y apellidos', fecha, DAYNAME(fecha) FROM vendedores;