# MOSTRAR LOS CLIENTES QUE MAS ENCARGOS HAN HECHO Y MOSTRAR CUANTOS HICIERON 
# ORDER BY 2 COLUMNA DEL SELECT 2 

SELECT cliente_id, COUNT(id) FROM encargos GROUP BY cliente_id ORDER BY 2 DESC LIMIT 2;