# CREAR UNA VISTA LLAMADA VENDEDORES A QUE INCLUIRA TODOS LOS VENDEDORES DEL GRUPO QUE SE LLAMA VENDEDORES A

CREATE VIEW vendedores AS 
SELECT * FROM vendedores WHERE grupo_id IN 
    (SELECT id FROM grupos WHERE nombre = 'Vendedores A');