# LISTAR TODOS VENDEDORES Y PARA CADA VENDEDOR MOSTRAR NOMBRE Y DIAS QUE LLEVA DE ALTA

SELECT nombre, DATEDIFF(CURDATE(), fecha) AS DIAS FROM vendedores;


UPDATE vendedores SET fecha='2018-12-03' WHERE id= 4;